name: Docker

on:
  workflow_run:
    workflows: ['Release']
    types: [completed]
    branches:
      - main

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Get version from Cargo.toml
        id: cargo_toml
        run: |
          cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version'
          echo "CURRENT_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build --platform linux/amd64 -t sophonhub/sophon-light-node:${{ env.CURRENT_VERSION }} .

      - name: Tag Docker Image
        run: |
          docker tag sophonhub/sophon-light-node:${{ env.CURRENT_VERSION }} sophonhub/sophon-light-node:latest

      - name: Push Docker Image
        run: |
          docker push sophonhub/sophon-light-node:${{ env.CURRENT_VERSION }}
          docker push sophonhub/sophon-light-node:latest