name: Docker

on:
  workflow_run:
    workflows: ['Release']
    types: [completed]
    branches:
      - main

jobs:

  build-and-push:
    name: Update Docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Get previous version
        id: previous_version
        run: |
          # Get the latest tag
          PREVIOUS_VERSION=$(git describe --tags --abbrev=0)
          
          # Extract the version number
          VERSION=$(echo $PREVIOUS_VERSION | sed 's/v//')
          
          echo "NEW_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build --platform linux/amd64 -t sophonhub/sophon-light-node:${{ env.NEW_VERSION }} .

      - name: Tag Docker Image
        run: |
          docker tag sophonhub/sophon-light-node:${{ env.NEW_VERSION }} sophonhub/sophon-light-node:latest

      - name: Push Docker Image
        run: |
          docker push sophonhub/sophon-light-node:${{ env.NEW_VERSION }}
          docker push sophonhub/sophon-light-node:latest