name: Docker

on:
  workflow_run:
    workflows: ['Release']
    types: [completed]
    branches:
      - main

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Get version from Cargo.toml
        id: version
        run: |
          cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version'
          VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          echo "::set-output name=version::$VERSION"
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          VERSION=${{ steps.version.outputs.version }}
          docker build --build-arg GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}} --platform linux/amd64 -t sophonhub/sophon-light-node:${{ steps.version.outputs.version }} .

      - name: Tag Docker Image
        run: |
          docker tag sophonhub/sophon-light-node:${{ steps.version.outputs.version }} sophonhub/sophon-light-node:latest

      - name: Push Docker Image
        run: |
          docker push sophonhub/sophon-light-node:${{ steps.version.outputs.version }}
          docker push sophonhub/sophon-light-node:latest